stages:
  - name: Publish
    when:
      branch: master
      event: [push, pull_request]
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          # pushRemote: true
          tag: naviapp-api:${CICD_EXECUTION_SEQUENCE}
          # registry: 313462697269.dkr.ecr.us-east-1.amazonaws.com
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yml
